[workspace]

[package]
name = "fuzz_tests"
version = "0.1.0"
description = "Created with Trident"
edition = "2021"

[dependencies]
borsh = "1.5.3"
solana-sdk = "~2.0"

anchor-lang = { version = "0.30.1", default-features = true, features = [
    "init-if-needed",
    "event-cpi"
] }
anchor-spl = { version = "0.30.1", default-features = true }
bytemuck = { version = "1.14", features = ["derive"] }
solana-program = "1.16.0"
jupiter_interface = "0.2.1"

[dependencies.trident-fuzz]
version = "0.11.0"

[[bin]]
name = "fuzz_0"
path = "fuzz_0/test_fuzz.rs"
